### ISSUE TITLE
[Feature Request] Script to add a shortcut to open the Link under cursor and jump to the First Big Heading or under the Frontmatter.

### ISSUE THREAD

**Issue by CrackheadoooObsidianUserooo** [nothingislost/obsidian-hover-editor#261] opened 2024-02-06 18:39 UTC

**Comment by pjeby** [comment] 2024-02-06 21:56
You can disable front matter showing in the Hover Editor by using CSS, or by setting "Properties in Front Matter" (in the Obsidian "Editor" settings) to "Hidden".

**Comment by pjeby** [comment] 2024-02-06 23:57
Closing as a duplicate of #258 - see there for more details on the current workaround and a CSS snippet you can use to hide properties in hover editors.

**Closed by pjeby** 2024-02-06 23:57 UTC
