### ISSUE TITLE
Click the window to the front of the rule is broken

### ISSUE THREAD

**Issue by jiajiala** [nothingislost/obsidian-hover-editor#245] opened 2023-11-05 10:43 UTC
![Honeycam 2023-11-05 18-36-39](https://github.com/nothingislost/obsidian-hover-editor/assets/73203026/d52cc92f-669e-4187-a7fe-57fad1910f1c)
I can't cha'k look at Windows 2 and 3 at the same time

Once I click on window 3, Window 1 goes to the top

**Comment by pjeby** [comment] 2023-11-06 02:43
0.11.15 has been released with a fix for this - it now tracks stacking order for more than two or three popups.  Let me know if it addresses your issue.

**Comment by jiajiala** [comment] 2023-11-06 13:01
![Honeycam 2023-11-06 20-57-54](https://github.com/nothingislost/obsidian-hover-editor/assets/73203026/df6c5307-9b76-425f-8fa9-d649f3f8be4a)
0.11.15, still cannot be used normally

When you click No. 1 in the figure, No. 4 also changes to the front, resulting in No. 1 and No. 2 can not be viewed at the same time



The desired experience is to click on the window to the front, leaving the other window levels unchanged

**Comment by pjeby** [comment] 2023-11-06 19:06
Are you sure you updated?  I just did in a sandbox vault and I cannot reproduce what you are showing.  Switching between hover editors does not change the order of any other editors besides the one you click on.  (At least in 0.11.15).

Please re-check that you are running 0.11.15 in the vault, and better yet, restart Obsidian to be sure.  If you can still reproduce the problem, please provide an exact step-by-step I can follow in a sandbox vault to produce the issue, since my simply opening four hover editors in sequence and clicking them does not produce the effects you're showing.

**Closed** 2023-11-08 11:11 UTC
