### ISSUE TITLE
Bug: not working with the calendar plugin

### ISSUE THREAD

**Issue by nicolasmarc1** [nothingislost/obsidian-hover-editor#67] opened 2022-03-25 22:25 UTC
Hi,
there is a small bug (not that important, just reporting it as the calendar plugin is pretty popular) with the calendar plugin, not sure if the issue is from the calendar plugin or hover editor side but when you try to hover on a day in the calendar plugin, it seems like it works for a millisecond and then it doesn't.  

Thanks.

**Comment by nothingislost** [comment] 2022-03-25 23:13
Confirmed. Thanks for the report. I blame this on @liamcain ;)

**Comment by liamcain** [comment] 2022-03-26 01:50
Hmm, this seems to be related to the "auto focus" setting. Works as expected if auto focus is disabled. 

/reassign @nothingislost

**Comment by nothingislost** [comment] 2022-03-26 23:47
The svelte generated targetEl being passed by Calendar does not exist in the DOM at the time onLinkHover is being called, causing the popover to close immediately:

![image](https://user-images.githubusercontent.com/89109712/160260127-978ce127-e6be-46b3-9bdb-8aaed149a235.png)

![image](https://user-images.githubusercontent.com/89109712/160260134-528d3594-7a75-431b-9220-dd682c852bdb.png)

I'm not familiar with Svelte but I can indeed see your elements getting removed if I set a DOM removal breakpoint on any calendar day and then change the active leaf.. doesn't even have to be a popover. 

You appear to have an active leaf change handler that is causing your DOM elements to be recreated on any active leaf change. When auto focus tries to change the active leaf, your handler kicks in and recreates the targetEL causing it to no longer be the element sent to onLinkHover.

Here's the call stack for the DOM removal: 

![image](https://user-images.githubusercontent.com/89109712/160260711-7bbd253a-1166-486b-911e-6c9eb0d967d6.png)

/reassign @liamcain

**Comment by nothingislost** [comment] 2022-03-26 23:55
I think for now I'm just going to disable auto focus for Calendar initiated hover previews. I'm guessing this is not going to be an easy thing to fix properly and it's probably affecting a number of people.

**Comment by nicolasmarc1** [comment] 2022-03-27 02:04
Oh i didn't see there was a way to turn off the "auto focus" in the settings, it works for me! + it will also avoid typing accidently in hovered notes! Thanks

**Comment by nothingislost** [comment] 2022-03-27 02:30
Cool, glad turning off auto focus was a viable solution for you. It's on my todo list to fix up the documentation to explain all the features properly.

I'm going to go ahead and close this since [0.6.3](https://github.com/nothingislost/obsidian-hover-editor/releases/tag/0.6.3) implemented ignoring auto focus if the hover parent is a Calendar view.

**Closed by nothingislost** 2022-03-27 02:30 UTC

**Comment by liamcain** [comment] 2022-03-27 14:24
Grr. Okay you win. I created a ticket on the calendar plugin repo to track. Will take a look soon.
