### ISSUE TITLE
Folding

### ISSUE THREAD

**Issue by ProStashio** [nothingislost/obsidian-hover-editor#227] opened 2023-07-13 19:00 UTC
I tend to fold my headers in my notes, especially ones with lots of content so I can easily open up the heading I need which has the content I am looking for.

Right now, the hover editor automatically opens all heads up.

I would like a setting to be able to disable this so I don't have all my heads open and instead lets me open just what I need

**Comment by pjeby** [comment] 2023-07-13 19:05
It's not doing that in my vault.  I can fold in the editor or the popup and either way it stays the way I put it last.  Maybe there's a plugin conflict in your vault?  Try it in the sandbox or a new vault with no plugins but HE.

**Comment by ProStashio** [comment] 2023-07-13 19:10
> 

I have tried in a fresh vault, it still does it. Have you tried doing it a few times? As it can sometimes not open them but others it does

**Comment by pjeby** [comment] 2023-07-14 01:54
If you have a note and procedure you can share, that I can use to consistently make it happen in a fresh vault, that would be helpful.  As it is, I haven't been able to make it happen on purpose even once.

**Comment by ProStashio** [comment] 2023-07-15 11:05
> If you have a note and procedure you can share, that I can use to consistently make it happen in a fresh vault, that would be helpful. As it is, I haven't been able to make it happen on purpose even once.

Like I said, it happens on a fresh vault

Here is an example:
https://youtu.be/udHFUJWdXM0

**Comment by pjeby** [comment] 2023-07-15 20:26
Well, the good news is I'm able to reproduce the problem.  The bad news is, the problem is in Obsidian's part of the code.

Basically, what's happening is that when you hover a link, HE sets up a new pane and loads the file into it, before you ever see anything.  So far, so good.  Then you move the cursor away, and HE goes, "oh well, we'll toss that pane, not gonna need it".  Obsidian then says, "Well, you're closing the pane, so we need to close the file.  And that means we need to save the fold state for the file.  And...  I have no fold state yet because I haven't opened yet, so let's just delete it."

I have no idea how to stop Obsidian doing that.  It appears the issue is that the markdown view is set up to *always* save the state when a pane gets closed, regardless of whether it finished opening.  If it didn't finish opening, then it always deletes the fold state.

About the only thing I can think of is to block Obsidian from saving the fold state for a file that was never actually visible on-screen (and perhaps had mouse interaction), assuming I can find a way to tell the difference between that and clicking on a fold in another pane.

Hm.  Okay, I think I have a fix - the downside of it is if you click on a heading to change folds, immediately move the mouse out of the hover editor, *and* have your close delay set to less than 500ms, then the last fold change may not be saved -- but any previously saved fold state won't be lost, only the changes you made less than half a second before the hover editor closes.

Fix will be in 0.11.13

**Comment by pjeby** [comment] 2023-07-15 20:36
Ok, I managed a better fix that only blocks the save when the hover editor was never opened to start with.  Give it a try and see what you think.

**Closed** 2023-07-15 20:36 UTC
