### ISSUE TITLE
Hopefully, the plugin will be able to play the video on the second screen

### ISSUE THREAD

**Issue by doriszhang2020** [nothingislost/obsidian-hover-editor#128] opened 2022-05-04 10:57 UTC
Thank you very much for developing such a useful plugin。This plug-in is able to play videos in suspension and use them to take study notes. But if you have two screens, you want to be able to put the video playback window on the second screen for easy note-taking. ShouldN't it be to give official advice to obsidian to support plugins outside the obsidian software interface?
![image](https://user-images.githubusercontent.com/104901283/166668683-e805ac6d-02be-4e36-89d4-ea9f8ca772d7.png)

**Comment by nothingislost** [comment] 2022-05-08 22:14
This is a duplicate of #7 and very unlikely to be possible any time in the near future due the complexity involved in making this work in Electron.

**Closed by nothingislost** 2022-05-08 22:14 UTC
