### ISSUE TITLE
[Feature request] Would like to add a new option to not show the context during live-preview

### ISSUE THREAD

**Issue by ZeaseTech** [nothingislost/obsidian-hover-editor#272] opened 2024-04-14 05:57 UTC
Sometimes the contextual content is a distraction for the preview content and it affects the concentration during live-preview, so I would like to add an option to show only the content included in the link and not the context of the link content.

**Comment by pjeby** [comment] 2024-04-14 07:24
This is a duplicate of #70; any progress will be posted there.

**Closed by pjeby** 2024-04-14 07:24 UTC
