### ISSUE TITLE
The window will disappear when used in excalidraw

### ISSUE THREAD

**Issue by jiajiala** [nothingislost/obsidian-hover-editor#291] opened 2024-11-15 08:16 UTC
https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/2041#issuecomment-2478190767
Here I have feedback excalidrawer, but it's said that the hover editor should be adjusted
Can you handle it
Thank you

**Comment by pjeby** [comment] 2024-11-16 18:30
I'm not able to reproduce this issue with either Obsidian 1.5.8 or 1.7.5, using Excalidraw 2.6.7 and the current Hover Editor.  I am creating a new drawing in the sandbox and then adding text to the drawing that says `[[Footnote]]` then hovering it with Ctrl and then dragging the created popup away.

Have you checked your Hover Editor settings to make sure your close delay isn't set too low?

**Comment by jiajiala** [comment] 2024-11-17 00:54
I downloaded the latest plug-in, not modifying any Settings, no css, but the hover window still disappears after drag
![2024_111708_5146](https://github.com/user-attachments/assets/838379dd-b711-4035-94ee-fba9294d962c)


![image](https://github.com/user-attachments/assets/97b89bdb-f615-4143-9d06-4debaf0b492f)

SYSTEM INFO:
	Obsidian version: v1.7.6
	Installer version: v1.7.6
	Operating system: Windows 10 Enterprise 10.0.19045
	Login status: not logged in
	Language: zh
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 98
	Plugins enabled: 2
		1: Hover Editor v0.11.21
		2: Excalidraw v2.6.7

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by pjeby** [comment] 2024-11-17 01:43
Yeah, it's actually Excalidraw's fault here.  It's deliberately closing any hover editor it opens, as soon as the mouse passes back over the Excalidraw drawing.  I have updated the issue over there asking the author why they're doing that and what they'd suggest as a workaround

**Comment by pjeby** [comment] 2024-11-17 01:46
Also, the issue was introduced in Excalidraw 2.5, so if you go back to an older version it is likely fine.

**Comment by jiajiala** [comment] 2024-11-17 01:48
Yes, I EXcalidraw no longer upgrade because of this bug, thank you for your time

**Comment by pjeby** [comment] 2024-12-08 22:27
Excalidraw 2.6.8, just released, fixes this issue.

**Closed by pjeby** 2024-12-08 22:27 UTC
