### ISSUE TITLE
You want the hover display to zoom in directly

### ISSUE THREAD

**Issue by jiajiala** [nothingislost/obsidian-hover-editor#233] opened 2023-08-26 05:29 UTC
like this
![image](https://github.com/nothingislost/obsidian-hover-editor/assets/73203026/6215450f-5b20-4812-82e0-b0715b61a326)

Direct zoom in
Links that help me focus more on the moment

**Comment by pjeby** [comment] 2023-08-26 06:25
Closing as duplicate of issue #70; please check existing issues before opening new ones, thanks.

**Closed by pjeby** 2023-08-26 06:25 UTC
